---
namespace: thinkphp_tech
name: thinkphp
description: Ansible collection for thinkphp, with nginx/php-fpm/swoole/mariadb/tidb etc.
version: "0.4.3"
readme: README.md
authors:
  - Bison 'goldeagle' Fan (bison@bitseed.cn)
dependencies: { }
license_file: LICENSE
tags:
  - php
  - apache
  - apache2
  - lamp
  - lnmp
  - nginx
  - thinkphp
  - swoole
  - debian
  - ubuntu
  - centos
  - kali
  - linux
  - rhel
  - fedora
  - tidb
  - mysql
  - nodejs
repository: https://github.com/thinkphp-tech/ansible-collection-thinkphp
documentation: https://github.com/thinkphp-tech/ansible-collection-thinkphp
homepage: "https://github.com/thinkphp-tech/ansible-collection-thinkphp"
issues: https://github.com/thinkphp-tech/ansible-collection-thinkphp/issues