---
php_version: 8.2
composer_version: 2.4.4
php_install_composer: true
php_install_pecl: false
php_install_redis: true
php_install_xdebug: false
php_install_xhprof: false
php_install_xlswriter: false
php_install_swoole: false
php_swoole_version: 4.8.2
php_swoole_url: "https://github.com/swoole/swoole-src/archive/v{{ php_swoole_version }}.zip"
