---
dependencies: []

galaxy_info:
  author: "bison 'goldeagle' fan"
  description: "rabbitmq role"
  company: "bitseed.cn"
  license: "license (Apache-2.0)"
  min_ansible_version: 2.4
  platforms:
    - name: centos
      versions:
        - 6
        - 7
    - name: debian
      versions:
        - all
    - name: fedora
      versions:
        - all
    - name: gentoo
      versions:
        - all
    - name: kali
      versions:
        - all
    - name: macos
      versions:
        - all
    - name: ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - mq
    - mqtt
    - rabbitmq