---
- name: Check if nodejs binary is installed
  stat:
    path: "/usr/local/bin/node"
  register: nodejs_bin

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
  when:
    - not nodejs_bin.stat.exists

- name: Install nodejs modules
  command: "npm i -g {{ item }}"
  loop:
    - n
    - yarn
    - gulp
    - grunt
    - "@vue/cli"