---

- name: Check if tiup is installed.
  stat:
    path: "/home/{{ tiup_user }}/.tiup/bin/tiup"
  register: tiup_is_installed

- name: Install tiup
  get_url:
    url: "https://tiup-mirrors.pingcap.com/tiup-linux-amd64.tar.gz"
    dest: "/tmp/tiup.tar.gz"
    mode: 0755
  when:
    - not tiup_is_installed.stat.exists

- name: Make tiup home dir
  file:
    path: "/home/{{ tiup_user }}/.tiup/bin"
    state: "directory"
    mode: "0755"
  when:
    - not tiup_is_installed.stat.exists

- name: Unpress tiup
  unarchive:
    src: "/tmp/tiup.tar.gz"
    dest: "/home/{{ tiup_user }}/.tiup/bin"
    mode: "0755"
    copy: no
  when:
    - not tiup_is_installed.stat.exists

- name: Remove template file
  file:
    path: /tmp/tiup.tar.gz
    state: absent
  when:
    - not tiup_is_installed.stat.exists

- name: Copy cluster configuration template file
  template:
    src: "{{ tidb_config_file }}"
    dest: "/home/{{ tiup_user }}/.tiup/bin/deploy.yaml"
    mode: "0644"

- name: Copy cluster installation script
  template:
    src: "deploy.sh.j2"
    dest: "/home/{{ tiup_user }}/.tiup/bin/deploy.sh"
    mode: "0755"