---
- name: Update && upgrade full packages
  apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install common softwares with update apt
  apt:
    pkg: [
      "byobu",
      "tmux",
      "htop",
      "iftop",
      "dstat",
      "sysstat",
      "hdparm",
      "iotop",
      "multitail",
      "net-tools",
      "unzip",
      "pixz",
      "bwm-ng",
      "vim",
      "zsh"
    ]
    state: present