---
- name: Install php-fpm and embeded extensions @Ubuntu
  apt:
    pkg: [
      "php{{ php_version }}",
      "php{{ php_version }}-bcmath",
      "php{{ php_version }}-bz2",
      "php{{ php_version }}-curl",
      "php{{ php_version }}-fpm",
      "php{{ php_version }}-gd",
      "php{{ php_version }}-mbstring",
      "php{{ php_version }}-mysql",
      "php{{ php_version }}-xml",
      "php{{ php_version }}-zip"
    ]
    state: present

- name: Check if Composer is installed.
  stat:
    path: "/usr/local/bin/composer"
  register: composer_bin
  when: php_install_composer

- name: Install php-redis extensions
  apt:
    pkg: "php-redis"
    state: present
  when: php_install_redis

- name: Install composer
  get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: "/usr/local/bin/composer"
    mode: 0755
  when:
    - php_install_composer
    - not composer_bin.stat.exists

- name: Install pecl
  apt:
    pkg: [
      "php{{ php_version }}-dev",
      "php-pear"
    ]
    state: present
  when: php_install_pecl

- name: Install xdebug
  shell: "yes '' | pecl install xdebug"
  register: xdebug_result
  changed_when: xdebug_result is succeeded
  failed_when: "not (('already installed' in xdebug_result.stdout) or ('install ok:' in xdebug_result.stdout))"
  when:
    - php_install_xdebug
    - php_install_pecl

- name: Enable xdebug with php-cli & php-fpm
  copy:
    src: 20-xdebug.ini
    dest: "/etc/php/{{ php_version }}/{{ item }}/conf.d"
    mode: "0777"
  loop:
      - cli
      - fpm
  notify:
    - restart php-fpm
  when: php_install_xdebug

- name: Install xhprof
  shell: "yes '' | pecl install xhprof"
  register: xhprof_result
  changed_when: xhprof_result is succeeded
  failed_when: "not (('already installed' in xhprof_result.stdout) or ('install ok:' in xhprof_result.stdout))"
  when:
    - php_install_xhprof
    - php_install_pecl

- name: Enable xhprof with php-cli & php-fpm
  copy:
    src: 20-xhprof.ini
    dest: "/etc/php/{{ php_version }}/{{ item }}/conf.d"
    mode: "0777"
  loop:
      - cli
      - fpm
  notify:
    - restart php-fpm
  when: php_install_xhprof

- name: Install Swoole
  shell: "yes '' | pecl install swoole"
  register: swoole_result
  changed_when: swoole_result is succeeded
  failed_when: "not (('already installed' in swoole_result.stdout) or ('install ok:' in swoole_result.stdout))"
  when: php_install_swoole

- name: Enable swoole with php-cli & php-fpm
  copy:
    src: 20-swoole.ini
    dest: "/etc/php/{{ php_version }}/{{ item }}/conf.d"
    mode: "0777"
  loop:
      - cli
      - fpm
  notify:
    - restart php-fpm
  when: php_install_swoole