---
- name: Add sury ppa source for apt
  apt_repository:
      repo: "ppa:ondrej/php"

- name: Copy php-fpm conf file
  copy:
    src: "php-fpm.conf"
    dest: "/etc/php/{{ php_version }}/fpm/php-fpm.conf"
    mode: "0777"
  loop:
      - "php-fpm.conf"

- name: Copy php-fpm ini file
  copy:
    src: "php.ini"
    dest: "/etc/php/{{ php_version }}/{{ item }}/php.ini"
    mode: "0777"
  loop:
      - cli
      - fpm

- name: Copy www conf file
  copy:
    src: "www.conf"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    mode: "0777"
  notify:
    - restart php-fpm

- name: Install php-fpm and embeded extensions @Ubuntu
  apt:
    pkg: [
      "libxml2-dev",
      "php{{ php_version }}",
      "php{{ php_version }}-bcmath",
      "php{{ php_version }}-bz2",
      "php{{ php_version }}-curl",
      "php{{ php_version }}-fpm",
      "php{{ php_version }}-cli",
      "php{{ php_version }}-gd",
      "php{{ php_version }}-mbstring",
      "php{{ php_version }}-mysql",
      "php{{ php_version }}-xml",
      "php{{ php_version }}-zip"
    ]
    state: present

- name: Check if Composer is installed
  stat:
    path: "/usr/local/bin/composer"
  register: composer_bin
  when: php_install_composer

- name: Install composer
  get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: "/usr/local/bin/composer"
    mode: 0755
  when:
    - php_install_composer
    - not composer_bin.stat.exists

- name: Install pecl
  apt:
    pkg: [
      "php{{ php_version }}-dev",
      "php-pear"
    ]
    state: present
  when: php_install_pecl

- name: Install php-redis extensions
  apt:
    pkg: "php{{ php_version }}-redis"
    state: present
  when: php_install_redis

- name: Install xdebug
  apt:
    pkg: "php{{ php_version }}-xdebug"
    state: present
  when:
    - php_install_xdebug

- name: Enable xdebug with php-cli & php-fpm
  copy:
    src: 20-xdebug.ini
    dest: "/etc/php/{{ php_version }}/{{ item }}/conf.d"
    mode: "0777"
  loop:
      - cli
      - fpm
  notify:
    - restart php-fpm
  when: php_install_xdebug

- name: Install xhprof
  apt:
    pkg: "php{{ php_version }}-xhprof"
    state: present
  when:
    - php_install_xhprof

- name: Enable xhprof with php-cli & php-fpm
  copy:
    src: 20-xhprof.ini
    dest: "/etc/php/{{ php_version }}/{{ item }}/conf.d"
    mode: "0777"
  loop:
      - cli
      - fpm
  notify:
    - restart php-fpm
  when: php_install_xhprof

- name: Install swoole
  include_tasks: "install-apt-swoole.yml"