---

- name: Install php-fpm and extensions
  apt:
    pkg: [
      "php{{ php_version }}",
      "php{{ php_version }}-bcmath",
      "php{{ php_version }}-curl",
      "php{{ php_version }}-fpm",
      "php{{ php_version }}-gd",
      "php{{ php_version }}-mbstring",
      "php{{ php_version }}-mysql",
      "php{{ php_version }}-xml",
      "php{{ php_version }}-zip"
    ]
    state: present